modLoader="javafml"
loaderVersion="[1,)"
license="BSD (3 clause)"
issueTrackerURL="https://github.com/gigaherz/Ender-Rift/issues"

[[mods]]
modId="enderrift"
version="${file.jarVersion}"
updateJSONURL="https://raw.githubusercontent.com/gigaherz/Ender-Rift/master/update.json"
displayName="Ender-Rift"
description='''
Bottomless Powered Inventory
'''
displayURL="https://github.com/gigaherz/Ender-Rift"
logoFile="logo.png"
authors="gigaherz"

[[dependencies.enderrift]]
   modId="neoforge"
   type="required"
   versionRange="[21.0.10-beta,)"
   ordering="NONE"
   side="BOTH"
[[dependencies.enderrift]]
   modId="minecraft"
   type="required"
   versionRange="[1.21,1.22)"
   ordering="NONE"
   side="BOTH"
[[dependencies.enderrift]]
   modId="waila"
   type="optional"
   versionRange="[0,)"
   ordering="AFTER"
   side="BOTH"